While working on the ConfigHandler for some reason PlayerActionsEvent broke without it having any connection to ConfigHandler and keeps throwing NoClassDefFoundError error for some god forsaken reason